components:
    schemas:
        Creator:
            description: https://www.schema.org/Creator
            properties:
                additionalName:
                    type: string
                familyName:
                    type: string
                givenName:
                    type: string
                id:
                    format: int64
                    type: integer
                image:
                    format: uri
                    type: string
                name:
                    type: string
                profileURL:
                    format: uri
                    type: string
            type: object
        Document:
            description: https://www.schema.org/Document
            properties:
                resourceType:
                    type: string
                source:
                    type: string
            type: object
        Results:
            description: https://www.schema.org/Results
            properties:
                resourceType:
                    type: string
                results:
                    type: string
            type: object
info:
    description: ""
    title: "Headless Search"
    version: v1.0
openapi: 3.0.1
paths:
    "/document/{index}/{uid}":
        get:
            parameters:
                - in: path
                  name: index
                  required: true
                  schema:
                      type: string
                - in: path
                  name: uid
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Document"
                    description: ""
            tags: ["Document"]
    "/search/{index}/{keywords}/{hidden}/{start}/{delta}":
        get:
            parameters:
                - in: path
                  name: index
                  required: true
                  schema:
                      type: string
                - in: path
                  name: keywords
                  required: true
                  schema:
                      type: string
                - in: path
                  name: hidden
                  required: true
                  schema:
                      type: string
                - in: path
                  name: start
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: delta
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Results"
                    description: ""
            tags: ["Results"]